[package]
name = "wezterm-android-ssh"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
serde = { version = "1.0", features = ["derive"] }
smol = "2.0"
thiserror = "1.0"
wezterm-ssh = { path = "../vendor/wezterm-ssh-android", default-features = false, features = ["libssh-rs", "vendored-openssl-libssh-rs"] }

[dev-dependencies]
serde_json = "1.0"
